export const Questions = [
    {
        prompt: "Which of this is not a Javascript framework or library?",
        optionA: "React",
        optionB: "Vue",
        optionC: "Angular",
        optionD: "Java",
        asnwer: "optionD",
    },
    {
        prompt: "React is a JavaScript library for building ___.",
        optionA: "Database",
        optionB: "Connectivity",
        optionC: "User Interface",
        optionD: "Design Platform",
        asnwer: "optionC",
    },
    {
        prompt: "User interface developed with React is made of small and isolated pieces of code called ___.",
        optionA: "Hook",
        optionB: "Component",
        optionC: "Function",
        optionD: "Snippet",
        asnwer: "optionB",
    },
    {
        prompt: "What are the two main types of components in React.js?",
        optionA: "Class based and functional",
        optionB: "Functional and stateful",
        optionC: "UI and container",
        optionD: "Presentational and container",
        asnwer: "optionA",
    },
    {
        prompt: "User interface developed with React is made of small and isolated pieces of code called ___.",
        optionA: "Hook",
        optionB: "Component",
        optionC: "Function",
        optionD: "Snippet",
        asnwer: "optionB",
    },
    {
        prompt: "A React component takes in parameters called ___?",
        optionA: "Attributes",
        optionB: "Events",
        optionC: "Props",
        optionD: "Children",
        asnwer: "optionC",
    },
    {
        prompt: "User interface developed with React is made of small and isolated pieces of code called ___.",
        optionA: "Hook",
        optionB: "Component",
        optionC: "Function",
        optionD: "Snippet",
        asnwer: "optionB",
    },
    {
        prompt: "To write HTML in react we make use of ___?",
        optionA: "React.createElement()",
        optionB: "HTTP",
        optionC: "XML",
        optionD: "JSX",
        asnwer: "optionD",
    },
    {
        prompt: "JSX Stands for ___?",
        optionA: "JavaScript Extension",
        optionB: "JavaScript Extreme",
        optionC: "JavaScript XML",
        optionD: "JavaScript XScript",
        asnwer: "optionC",
    },
    {
        prompt: "React DOM uses ___ case property naming convention?",
        optionA: "Camel",
        optionB: "Pascal",
        optionC: "Snake",
        optionD: "Kebab",
        asnwer: "optionA",
    },
    {
        prompt: "___ are the smallest building blocks of React apps.",
        optionA: "Tags",
        optionB: "Component",
        optionC: "Elements",
        optionD: "JSX",
        asnwer: "optionC",
    },
    {
        prompt: "One of these hooks is used to imitate lifecycles",
        optionA: "useState",
        optionB: "useEffect",
        optionC: "useReducer",
        optionD: "useCycles",
        asnwer: "optionB",
    },
];